return {
  ["workshop-1378549454"]={
    configuration_options={
      ["MemSpikeFix:"]=false,
      MemSpikeFixmaster_override=true,
      ["MemSpikeFixworkshop-1467214795"]="default",
      ["MemSpikeFixworkshop-2302837868"]="default",
      ["MemSpikeFixworkshop-3018652965"]="default",
      ["MemSpikeFixworkshop-351325790"]="default",
      craftinghighlight=false 
    },
    enabled=true 
  },
  ["workshop-1467214795"]={
    configuration_options={
      ["Cut Content Restoration"]=false,
      caveid=false,
      devmode=false,
      droplootground=true,
      dynamicmusic=true,
      forestid=false,
      leif_jungle=false,
      limestonerepair=true,
      locale=false,
      newloot="all",
      newplayerboats=true,
      octopuskingtweak=true,
      octopustrade=true,
      oldwarly=false,
      pondfishable=true,
      quickseaworthy=false,
      shipwreckedid=false,
      slotmachineloot=true,
      tuningmodifiers=true,
      volcanoid=false,
      windgustable="all",
      windstaffbuff=2,
      ["人物修改"]=false,
      ["多(三层以上)世界选项,不要乱改"]=false,
      ["杂项"]=false,
      ["游戏功能"]=false,
      ["物品和建筑"]=false,
      ["生物改变"]=false 
    },
    enabled=true 
  } 
}