--Wendy's speech file
return {
	ACTIONFAIL =
	{
		REPAIRBOAT =
		{
			GENERIC = "It's already in better shape than I am.",
		},
		EMBARK = 
		{
			INUSE = "The ship has left port without me!",
		},
		INSPECTBOAT = 
		{
			INUSE = GLOBAL.STRINGS.CHARACTERS.GENERIC.ACTIONFAIL.STORE.INUSE
		},
		OPEN_CRAFTING  = 
		{
			FLOODED = "It's broken, like my soul.",
		},
	},

	ANNOUNCE_MAGIC_FAIL = "It's not doing anything. Sigh.",

	ANNOUNCE_SHARX = "I am pursued by miscreants!",

	ANNOUNCE_TREASURE = "A treasure map... How exciting!",
	ANNOUNCE_TREASURE_DISCOVER = "Treasure... How exciting!",
	ANNOUNCE_MORETREASURE = "Another map... Less exciting!",
	ANNOUNCE_OTHER_WORLD_TREASURE = "This is a guide to a faraway land.",
	ANNOUNCE_OTHER_WORLD_PLANT = "It doesn't belong here. Just like me.",

	ANNOUNCE_IA_MESSAGEBOTTLE =
	{
		"All things fade, in time...",
	},
	ANNOUNCE_VOLCANO_ERUPT = "Not with a bang, but with an ERUPTION!",
	ANNOUNCE_MAPWRAP_WARN = "Perhaps I'll sail from the edge of the earth.",
	ANNOUNCE_MAPWRAP_LOSECONTROL = "Watch as I sail straight into the maw of death!",
	ANNOUNCE_MAPWRAP_RETURN = "I return once again to this world.",
	ANNOUNCE_CRAB_ESCAPE = "It eluded death another day.",
	ANNOUNCE_TRAWL_FULL = "The sea offers up its bounty.",
	ANNOUNCE_BOAT_DAMAGED = "This vessel is damaged. I can relate.",
	ANNOUNCE_BOAT_SINKING = "I will soon face a watery grave.",
	ANNOUNCE_BOAT_SINKING_IMMINENT = "I surrender myself to the depths!",
	ANNOUNCE_WAVE_BOOST = "Joy...",

	ANNOUNCE_WHALE_HUNT_BEAST_NEARBY = "The behemoth reveals itself!",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL = "Like Ishmael, my hunt is doomed.",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL_SPRING = "I will find you, beast!",

	DESCRIBE = {
		SEAWEED_STALK = "They desire a watery grave.", --copied from the Wikia because I couldn't find it in the game files. -M

		SOLOFISH_DEAD = "It has shed its earthly tether.",
		
		GHOST_SAILOR = "He has found no respite.",
		FLOTSAM = "I can't quite reach it.",
		SUNKEN_BOAT =
		{
			ABANDONED = "Are you all alone?",
			GENERIC = "Oh, the stories this ship could tell.",
		},
		SUNKEN_BOAT_BURNT = "A poetic end.",
		BISQUE = "Feed the body, starve the soul...",
		SHARKFINSOUP = "It's tasted a mortal escape. I'll be tasting it.",
		JELLYOPOP = "Death comes to us all. Sometimes on a stick.",
		
		BOAT_ENCRUSTED = "A vessel of aquatic death.",
		BABYOX = "Cold, vacant eyes...",
		BALLPHINHOUSE = "A wretched den of joviality.",
		DORSALFIN = "Remnants of destruction.",
		NUBBIN = "Bare and completely devoid of life.",
		CORALLARVE = "What a foul worm.",
		RAINBOWJELLYFISH = "This jellyfish is much more vibrant than the others.",
		RAINBOWJELLYFISH_PLANTED = "It seems so content.",
		RAINBOWJELLYFISH_DEAD = "Death has come for it.",
		RAINBOWJELLYFISH_COOKED = "Beautiful, even in death.",
		RAINBOWJELLYJERKY = "Its death means my life.",
		WALL_ENFORCEDLIMESTONE = "Slimy on top.",
		WALL_ENFORCEDLIMESTONE_ITEM = "It would be more useful if I placed it.",
		CROCODOG = "If I stuck my head in its jaws, that would be the end.",
		POISONCROCODOG = "Pierce me with your venomous fangs...",
		WATERCROCODOG = "A damp death awaits me...",
		QUACKENBEAK = "Its gnashing days are over.",
		QUACKERINGRAM = "I can be assertive, when need be.",

		CAVIAR = "I took their life to sustain my own.",
		CORMORANT = "She is surely an ill omen.",

		PURPLE_GROUPER = "A pitiful creature.",
		PIERROT_FISH = "The stripes symbolize its emotional imprisonment.",
		NEON_QUATTRO = "It misses its watery home.",
		
		PURPLE_GROUPER_COOKED = "Rest now, fish spirit.",
		PIERROT_FISH_COOKED = "Don't lose your head.",
		NEON_QUATTRO_COOKED = "I've... eaten worse...",

		FISH_FARM = 
		{
			EMPTY = "Life can't come from nothing... I need something...",
			STOCKED = "Life needs time to blossom.",
			ONEFISH = "Look, Abby. We have a visitor.",
			TWOFISH = "Abby... There's more now...",
			REDFISH = "Do they know I'm watching?",
			BLUEFISH  = "They shall never taste freedom.",
		},

		ROE = "The beginnings of life...",
		ROE_COOKED = "I spared them the pain of hatching.",
		
		SEA_YARD = 
		{
			ON = "It wards off the inevitable decay.",
			OFF = "Decay will surely come for my ships now.",
			LOWFUEL = "It is close to giving up, just like me.",
		},
		
		SEA_CHIMINEA =
		{
			EMBERS = "It will soon be snuffed out.",
			GENERIC = "Afloat upon its own demise.",
			HIGH = "A healthy fire rages within.",
			LOW = "It tenuously clings to this world.",
			NORMAL = "It burns, for now.",
			OUT = "Its warmth and light were fleeting.",
		}, 

		TAR = "Thick, with a stench of corruption.",
		TAR_EXTRACTOR =
		{
			ON = "It is pulling sludge from the depths.",
			OFF = "It's off...",
			LOWFUEL = "It won't last much longer. Me neither.",
		},
		TAR_POOL = "Corruption oozes from beneath.",

		TARLAMP = "It takes vileness and makes it light.",
		TARSUIT = "To make my outside match my inside.",
		TAR_TRAP = "A recipe for a slow painful death.",
		
		TROPICALBOUILLABAISSE = "A brief respite from the hunger.",

		SEA_LAB = "Do I dare plumb the sea's dark knowledge?",
		WATERCHEST = "Treasures suspended over the bottomless abyss.",
		QUACKENDRILL = "Corruption spills forth from the depths.",
		HARPOON = "It brings naught but death.",
		MUSSEL_BED = "They yearn for the deep.",
		ANTIVENOM = "A potion to stave off the sickness.",
		POISONBALM = "In case I don't want to succumb to poison. Unlikely.",
		VENOMGLAND = "Their dead drop the cure to their sickness.",
		BLOWDART_POISON = "Sending ill will with a whisper.",
		OBSIDIANMACHETE = "The blade both bites and burns.",
		SPEARGUN_POISON = "Each shot inflicts a suffocating sickness.",
		OBSIDIANSPEARGUN = "I deliver fire with the pull of a trigger.",
		LUGGAGECHEST = "A very dapper item storage system.",
		PIRATIHATITATOR =
		{
			GENERIC = "This is but a step from madness.",
			BURNT = "Whatever it was, it's burnt now.",
		},
		COFFEEBEANS = "These look stimulating.",
		COFFEE = "Dark. Bitter...",
		COFFEEBEANS_COOKED = "Who knew the will to live came in bean form?",
		COFFEEBUSH =
		{
			BARREN = "It could use a pick me up.",
			WITHERED = "I feel the same way.",
			GENERIC = "A beany gift from the heavens.",
			PICKED = "All wounds heal in time, little bush.",
		},
		COFFEEBOT = "I take mine black.",--unused
		MUSSEL = "You cannot hide beneath the waves, meat!",
		MUSSEL_FARM =
		{
			GENERIC = "They don't look that tough to me.",
			STICKPLANTED = "Ha!",
		},
		
		MUSSEL_STICK = "The mussels cling to this stick. Fools.",
		LOBSTER = "It would taste excellent dead and smothered in butter.",
		LOBSTERHOLE = "A lobster dinner lives there.",
		WOBSTERBISQUE = "I would like a spoon.",
        WOBSTERDINNER = "Its death will give me life.",
		SEATRAP = "Come, creatures of the sea! Enjoy a lovely snack!",
		SANDCASTLE =
		{
			GENERIC = "Its beauty will undoubtedly succumb to the tide.",
			SAND = "If only molding the sands of time were so easy.",
		},
		BOATREPAIRKIT = "This could save a boat from destruction, and me with it.",
		
		BALLPHIN = "What a chipper little fellow. Does he know life has no meaning?",
		BOATCANNON = "It brings low death to high seas!",
		BOTTLELANTERN = "The light of life. Trapped.",
		BURIEDTREASURE = "Dead people's stuff.",
		BUSH_VINE =
		{
			BURNING = "An inevitable end.",
			BURNT = "I think it looks better like this.",
			CHOPPED = "Your sacrifice will not be in vain.",
			GENERIC = "It's quite pretty.",
		},
		CAPTAINHAT = "No living soul commands the sea...",
		COCONADE =
		{
			BURNING = "Fire in the hole!",
			GENERIC = "I hold someone's explosive death in my hands.",
		},
		CORAL = "The sea gives them life, and yet they stretch to escape it.",
		ROCK_CORAL = "The coral grows to escape the sea.",
		CRABHOLE = "A hole is just a grave that has yet to be covered.",
		CUTLASS = "It will feel no guilt from the kill. It is but a tool.",
		DUBLOON = "The currency of scallywags.",
		FABRIC = "I wonder if the bamboo finds this new form agreeable?",
		FISHINHOLE = "The meat swims round and round. Oblivious.",
		GOLDENMACHETE = "What a fancy blade to ruin bamboo with!",
		JELLYFISH = "How can such a curious thing even live?",
		JELLYFISH_DEAD = "It was a painless death. The beast had no nervous system.",
		JELLYFISH_COOKED = "It's sort of like gelatin.",
		JELLYFISH_PLANTED = "The sting isn't deadly. Only painful.",
		JELLYJERKY = "So... tough.",
		
		ROCK_LIMPET =
		{
			GENERIC = "Those look edible... sort of.",
			PICKED = "I picked it clean.",
		},
		BOAT_LOGRAFT = "This looks heavy, slow and dangerous.",
		MACHETE = "This is a lot of blade.",
		IA_MESSAGEBOTTLEEMPTY = "Empty. Like my soul.",
		MOSQUITO_POISON = "As if bloodsucking wasn't low enough, this one leaves you sick.",
		OBSIDIANCOCONADE = "The tree's children will raze the world.",
		OBSIDIANFIREPIT =
		{
			EMBERS = "Don't give up, little flame!",
			GENERIC = "A flame to keep the horrors at bay.",
			HIGH = "This fire burns with passion!",
			LOW = "It's losing the will to go on.",
			NORMAL = "It burns with the anger of its maker.",
			OUT = "I'd better relight this.",
		},
		OX = "You are heavy with meat. Let me lighten your load.",
		PIRATEHAT = "That hat of a cutthroat killer. I admire it.",
		BOAT_RAFT = "Perhaps if I ride upon the waves I shall join my sister.",
		BOAT_ROW = "I wonder how many leagues this can convey me?",
		SAIL_PALMLEAF = "Harness the wind and fly to... nowhere.",
		SANDBAG_ITEM = "Looks like a back injury waiting to happen.",
		SANDBAG = "They hold back ruin. For a time...",
		SEASACK = "It slows the rot and decay.",
		SEASHELL_BEACHED = "She sells seashells... oh, what's the point.",
		SEAWEED = "Even the sea is infested by weeds.",
		
		SEAWEED_PLANTED = "A hearty weed.",
		SLOTMACHINE = "Ah, this seems a sensible test of fate.",
		SNAKE_POISON = "The only thing worse than a snake is a poison one.",
		SNAKESKIN = "It shed its skin, with my assistance.",
		SNAKESKINHAT = "A hat of trophies, wrenched from the dead!",
		SOLOFISH = "Such graceful swimming. Such tasty flesh.",
		SPEARGUN = "It deals death from a distance!",
		SWORDFISH = "This fish cuts death with its face!",
		IA_TRIDENT = "The peoples that forged this are long dead.",
		SUNKEN_BOAT_TRINKET_1 = "I just use it as a paperweight.",
		SUNKEN_BOAT_TRINKET_2 = "What sort of simple mind would be amused by this?",
		SUNKEN_BOAT_TRINKET_3 = "It's completely drenched.",
		SUNKEN_BOAT_TRINKET_4 = "I have no idea what that is.",
		SUNKEN_BOAT_TRINKET_5 = "What a cliche.",
		TRINKET_IA_13 = "Maybe if I drank this stuff I'd return to my sister.",
		TRINKET_IA_14 = "If I pushed a pin into this doll, who would feel it?",
		TRINKET_IA_15 = "Whoever this belonged to isn't walking anymore.",
		TRINKET_IA_16 = "Whatever this belonged to met a bad end.",
		TRINKET_IA_17 = "Whoever wore this is surely dead.",
		TRINKET_IA_18 = "A remnant of a civilization lost at sea.",
		TRINKET_IA_19 = "The owner's brain has surely clouded for good by now.",
		TRINKET_IA_20 = "I just use it as a paperweight.",
		TRINKET_IA_21 = "What sort of simple mind would be amused by this?",
		TRINKET_IA_22 = "Very DIY.",
		TRINKET_IA_23 = "How unfortunate.",
		EARRING = "But no ear...",
		TURBINE_BLADES = "No longer turning.",
		TURF_BEACH = "Sand does not make good grave fill.",
		TURF_JUNGLE = "A gnarled and twisted surface.",
		VOLCANO_ALTAR =
		{
			GENERIC = "It's closed for business.",
			OPEN = "Let the sacrifice begin!",
		},
		VOLCANO_ALTAR_BROKEN = "Shame. No more weapons of fire to forge.",
		WHALE_BLUE = "It looks sad.",
		WHALE_CARCASS_BLUE = "Something this big and dead will surely stink.",
		WHALE_CARCASS_WHITE = "It is very big. And very dead.",
		
		ARMOR_SNAKESKIN = "A jacket of dead flesh. Fashionable.",
		SAIL_CLOTH = "With sail in hand I shall beat a hasty escape. But to where?",
		DUG_COFFEEBUSH = "Do you wish to return to the ground?",
		LAVAPOOL = "This pool churns with the volcano's anger!",
		BAMBOO = "Green sticks... who cares...",
		AERODYNAMICHAT = "I cut through the air!",
		POISONHOLE = "The ground belches death.",
		BOAT_LANTERN = "To see the vast nothingness in the black of night.",
		SWORDFISH_DEAD = "Its sword face couldn't save it...",
		LIMPETS = "They eat of the rock. I eat of them.",
		OBSIDIANAXE = "It cuts and burns.",
		COCONUT = "What secrets must this fruit hide beneath its armor?",
		COCONUT_SAPLING = "I was expecting a darker secret.",
		COCONUT_COOKED = "It's a little sweet.",
		BERMUDATRIANGLE = "Dark energy courses through these mysterious portals...",
		SNAKE = "Devoid of arms or legs. I'd be angry too.",
		SNAKEOIL = "This fills me with a sense of mistrust.",
		ARMORSEASHELL = "Armor made of the homes of dead goo.",
		SNAKE_FIRE = "The children of the volcano. They breath its fire.",
		MUSSEL_COOKED = "I sure strongarmed this mussel.",
		
		PACKIM_FISHBONE = "A dead fish thingy. Looks important.",
		PACKIM = "I would not trust him with a fish, but perhaps my junk...",
		
		ARMORLIMESTONE = "Heavy...",
		TIGERSHARK = "Orange striped death on water!",
		WOODLEGS_KEY1 = "What unfortunate soul donated their bones for this?",
		WOODLEGS_KEY2 = "It probably unlocks something fancy.",
		WOODLEGS_KEY3 = "What do you open?",
		WOODLEGS_CAGE = "At least his soul escaped.",
		OBSIDIAN_WORKBENCH = "Ah, this is where fiery items are forged.",
		
		NEEDLESPEAR = "One could end it all with this.",
		LIMESTONENUGGET = "When coral dies it hardens into stone.",
		DRAGOON = "Would make a lovely pet, if not for the whole \"murder\" thing.",
		
		ICEMAKER =
		{
			OUT = "It gave up.",
			VERYLOW = "It's running on fumes.",
			LOW = "It seems a little depressed.",
			NORMAL = "It's feeling okay.",
			HIGH = "It's in great shape.",
		},
		
		DUG_BAMBOOTREE = "Will you wither, or live?",
		BAMBOOTREE =
		{
			BURNING = "Alas, nobody wins.",
			BURNT = "So it goes.",
			CHOPPED = "I've won this round.",
			GENERIC = "I can bend it to my will.",
		},
		
		JUNGLETREE =
		{
			BURNING = "I should probably step back.",
			BURNT = "It's turned a beautiful shade of black.",
			CHOPPED = "What lovely destruction.",
			GENERIC = "A jungle tree.",
		},
		SHARK_GILLS = "No one's breathing through these now.",
		LEIF_PALM = "Oh... no...", -- "A lumbering beast.",
		OBSIDIAN = "A stone forged of fire.",
		BABYOX = "Youth is but a grain of sand, slipping through the hourglass.",
		STUNGRAY = "They fly to escape their own hideousness.",
		SHARK_FIN = "It won't be needing this anymore.",
		FROG_POISON = "A poisonous lick from that and this nightmare will end.",
		BOAT_ARMOURED = "A boat that can take a bite or two.",
		ARMOROBSIDIAN = "Is it wise to don a suit of fire stone?",
		BIOLUMINESCENCE = "Life takes such curious forms! Yet death claims them all.",
		SPEAR_POISON = "One jab and they'll be retching.",
		SPEAR_OBSIDIAN = "Jabbing with fire.",
		SNAKEDEN =
		{
			BURNING = "Nothing pretty ever lasts.",
			BURNT = "I think it looks better like this.",
			CHOPPED = "Your sacrifice will not be in vain.",
			GENERIC = "It's quite pretty.",
		},
		TOUCAN = "It sings a tortured song.",
		IA_MESSAGEBOTTLE = "The last, desperate act of a doomed soul. In a bottle.",
		SAND = "I wonder if the sand knows of its own insignificance?",
		SANDDUNE = "This looks impermanent.",
		PEACOCK = "Such pretty feathers hiding tasty meat!",
		VINE = "Unruly life.",
		SUPERTELESCOPE = "I can see so much more useless nothing.",
		SEAGULL = "The scavengers of land and sea.",
		SEAGULL_WATER = "As if it weren't bad enough that they foul the air.",
		PARROT = "Is it my ears, or does the creature chatter a lonesome monologue?",
		ARMOR_LIFEJACKET = "I'd prefer a dry grave, thank you.",
		WHALE_BUBBLES = "Looks like a fish with a gas problem.",
		ARMOR_WINDBREAKER = "The wind's tendrils cannot hold me!",
		SEAWEED_COOKED = "Better, but it's still a weed.",
		BOAT_CARGO = "This transports more junk to nowhere.",
		GASHAT = "This hat prevents me from breathing in death.",
		ELEPHANTCACTUS = "It's sad and painful.",
		DUG_ELEPHANTCACTUS = "Do I have to carry it?",
		ELEPHANTCACTUS_ACTIVE = "This plant doesn't want anyone to touch it.",
		ELEPHANTCACTUS_STUMP = "It's hiding below.",
		SAIL_FEATHER = "Those dumb birds sure make a speedy sail.",
		WALL_LIMESTONE_ITEM = "A wall made of living coral... No longer.",
		JUNGLETREESEED = "It's a parcel of potential.",
		JUNGLETREESEED_SAPLING = "There's no going back, now.",
		VOLCANO = "The mountain that spews death to the heavens!",
		IRONWIND = "If I'm lucky I'll sail off the edge of the earth.",
		SEAWEED_DRIED = "It keeps longer like this. Tastes better too.",
		TELESCOPE = "To peer over the horizon with an unabiding longing.",
		
		DOYDOY = "This bird seems too stupid to be alive.",
		DOYDOYBABY = "How cute. And dumb.",
		DOYDOYEGG = "What a dumb egg.",
		DOYDOYEGG_CRACKED = "This is probably a mercy.",
		DOYDOYFEATHER = "A spot of color in a dreary world.",
		
		PALMTREE =
		{
			BURNING = "I should probably step back.",
			BURNT = "It's turned a beautiful shade of black.",
			CHOPPED = "What lovely destruction.",
			GENERIC = "Its fruit bestows life, but only if I kill it.",
		},
		PALMLEAF = "I bet this leaf mourns its fallen tree.",
		CHIMINEA = "This shall protect a fire from the wind's prying fingers.",
		DOUBLE_UMBRELLAHAT = "This seems excessive.",
		CRAB =
		{
			GENERIC = "This island has a crustacean infestation.",
			HIDDEN = "You can't hide from your problems forever. I've tried.",
		},
		TRAWLNET = "A way to wrest items from the sea's grip.",
		TRAWLNETDROPPED =
		{
			SOON = "Its journey is almost at an end.",
			SOONISH = "It's started its journey into the depths.",
			GENERIC = "What creatures will this wrest from the ocean?",
		},
		VOLCANO_EXIT = "Shall I leave this place of hot death?",
		SHARX = "Terror of the sea!",
		SEASHELL = "Whatever used to live in this is probably dead now.",
		MAGMAROCK = "The earth's guts, cooled and ready for mining.",
		MAGMAROCK_GOLD = "The earth's guts, cooled and ready for mining.",
		CORAL_BRAIN_ROCK = "That's one smart-looking plant.",
		CORAL_BRAIN = "Is that what I look like inside?",
		SHARKITTEN = "I could see myself growing old with a houseful of these.",
		SHARKITTENSPAWNER =
		{
			GENERIC = "I smell... kitty litter?",
			INACTIVE = "A sizable sandpile.",
		},
		LIVINGJUNGLETREE = "This unassuming tree looks exactly how I feel.",
		WALLYINTRO_DEBRIS = "The ship has been obliterated.",
		MERMFISHER = "I commend this creature's commitment to cannibalism.",
		PRIMEAPE = "His joviality is almost endearing. Almost.",
		PRIMEAPEBARREL = "Looks filthy.",
		BARREL_GUNPOWDER = "This is a safety hazard. Good.",
		PORTAL_SHIPWRECKED = "Like my beloved sister, I can never return.",
		MARSH_PLANT_TROPICAL = "What a pathetic sprout.",
		PIKE_SKULL = "I guess he chose Not-To-Be.",
		PALMLEAF_HUT = "A welcome respite.",
		LOBSTER_DEAD = "It's met its maker. I've met my lunch.",
		MERMHOUSE_FISHER = "How quaint.",
		WILDBORE = "What's it got to be angry about?",
		PIRATEPACK = "This should help me carry more junk.",
		TUNACAN = "This is plainly false advertising.",
		MOSQUITOSACK_YELLOW = "What a lovely shade of puke-yellow.",
		SANDBAGSMALL = "Dense and heavy.",
		FLUP = "That's too many eyes!",
		OCTOPUSKING = "I envy his contentment.",
		OCTOPUSCHEST = "That doesn't look like a reliable place to store things.",
		GRASS_WATER = "Damp.",
		WILDBOREHOUSE = "Hopefully they won't invite me in.",
		TURF_SWAMP = "It's just ground.",
		FLAMEGEYSER = "It's hot!",
		KNIGHTBOAT = "That thing has anger issues!",
		MANGROVETREE_BURNT = "What a shame.",
		TIDAL_PLANT = "It's sharp.",
		WALL_LIMESTONE = "A wall of the dead to beat back the living.",
		LOBSTER_DEAD_COOKED = "It's a feast!",
		BLUBBERSUIT = "Disturbing, but cozy.",
		BLOWDART_FLUP = "Now when I shoot someone a look it'll pack a punch!",
		TURF_MEADOW = "It's just ground.",
		TURF_VOLCANO = "It's just ground.",
		SWEET_POTATO = "Sweet. Just like me.",
		SWEET_POTATO_COOKED = "Would that my despair tasted half so sweet.",
		SWEET_POTATO_PLANTED = "That looks like lunch.",
		SWEET_POTATO_SEEDS = "Perhaps these could give new life.",
		BLUBBER = "The perfect meal for a blubbering fool.",
		TELEPORTATO_SW_RING = "This ring's probably not for wearing.",
		TELEPORTATO_SW_BOX = "Looks a little screwy.",
		TELEPORTATO_SW_CRANK = "It seems incomplete.",
		TELEPORTATO_SW_POTATO = "What possible use could this have?",
		TELEPORTATO_SW_BASE = "It's missing something.",
		VOLCANOSTAFF = "The fiery breath of the volcano is mine to command!",
		THATCHPACK = "I was always destined to carry a heavy load.",
		SHARK_TEETHHAT = "Chic, yet fearsome.",
		TURF_ASH = "It's just ground.",
		BOAT_TORCH = "How illuminating.",
		MANGROVETREE = "It's quite elegant.",
		HAIL_ICE = "Frozen like my heart.",
		FISH_TROPICAL = "It's offensively bright.",
		TIDALPOOL = "When I gaze into this limpid pool I dream I can see Abigail.",
		WHALE_WHITE = "There is the hate of life burning in its eyes!",
		VOLCANO_SHRUB = "A wretched shadow of its former self.",
		ROCK_OBSIDIAN = "Do you burn to the touch?",
		ROCK_CHARCOAL = "I can't tell what you used to be.",
		DRAGOONDEN = "Cruel hearts dwell within.",
		WILBUR_UNLOCK = "His finery does nothing to mask the smell.",
		WILBUR_CROWN = "Monarchs must have tiny heads.",
		TWISTER = "Nature is very angry!",
		TWISTER_SEAL = "It has no awareness of the ills of this world.",
		MAGIC_SEAL = "It pulses with unknown power.",
		WINDSTAFF = "It's... a stick.",
		WIND_CONCH = "A terrifying force of nature contained within a delicate shell.",
		DRAGOONEGG = "Hard to imagine this would birth forth such a horrific monster.",
		BUOY = "Float on, little friend.",
		TURF_SNAKESKIN = "It's just ground.",
		DOYDOYNEST = "With each of these the island gets dumber. And meatier.",
		ARMORCACTUS = "It makes me as prickly outside as I am inside!",
		BIGFISHINGROD = "Ye be warned, creatures of the sea. Death cometh to you.",
		BRAINJELLYHAT = "Does this make my brain look big?",
		COCONUT_HALVED = "Two halves that were once whole. Where are you now, Abigail?",
		CRATE = "It's just a box.",
		DEPLETED_BAMBOOTREE = "It clings to life. Barely.",
		DEPLETED_BUSH_VINE = "The strangling vines have themselves been strangled.",
		DEPLETED_GRASS_WATER = "No more.",
		DOYDOYEGG_COOKED = "Not extinct yet, though not from lack of trying.",
		DRAGOONHEART = "This heart's as dead as my own, although much warmer.",
		DRAGOONSPIT = "Yuck!",
		DUG_BUSH_VINE = "Planting you again would be the true cruelty.",
		KRAKEN = "Kneel to me, foul beast!",
		KRAKENCHEST = "What wonders lie within?",
		KRAKEN_TENTACLE = "Oh gee, I'm Quacken in my boots.",
		MAGMAROCK_FULL = "The earth's guts, cooled and ready for mining.",
		MAGMAROCK_GOLD_FULL = "The earth's guts, cooled and ready for mining.",
		MONKEYBALL = "It makes me feel less alone. Plus I can throw it.",
		MUSSELBOUILLABAISE = "My mouth's watering just looking at it.",
		MYSTERYMEAT = "That's grotesque.",
		OXHAT = "Dashing.",
		OX_FLUTE = "That I might play a tune to soothe my troubled heart.",
		OX_HORN = "It's been severed from its owner.",
		PARROT_PIRATE = "If I whispered my secrets to it, would it keep them safe?",
		PEG_LEG = "But where's the rest of the peg-person?",
		PIRATEGHOST = "A future friend of Abigail's?",
		SANDBAGSMALL_ITEM = "A bag of dirt I can carry.",
		SHADOWSKITTISH_WATER = "Yikes.",
		SHIPWRECKED_ENTRANCE = "Curiouser and curiouser.",
		SHIPWRECKED_EXIT = "Onward to the next adventure.",
		SAIL_SNAKESKIN = "Gross, but efficient.",
		SPEAR_LAUNCHER = "Why throw a spear when you can shoot it?",
		SWEETPOTATOSOUFFLE = "Delicate, but delicious.",
		SWIMMINGHORROR = "I want to put some distance between myself and that!",
		TIGEREYE = "Tyger, tyger, burning bright...",
		TURF_MAGMAFIELD = "It's just ground.",
		TURF_TIDALMARSH = "It's just ground.",
		VOLCANO_ALTAR_TOWER = "A beautiful altar of death.",
		WATERYGRAVE = "I'm not above raiding a grave for loot.",
		WHALE_TRACK = "Whale, ho!",
		WILDBOREHEAD = "What lovely decor.",
		BOAT_WOODLEGS = "A seaworthy vessel if ever there was one!",
		WOODLEGSHAT = "Haughty seadog couture.",
		SAIL_WOODLEGS = "I adore the design.",
		SHIPWRECK = "Its crew is probably dead...",
		INVENTORYGRAVE = "Would they mind if I crawled in with them?",
		INVENTORYMOUND = "Would they mind if I crawled in with them?",
		LIMPETS_COOKED = "Depressing.",
		RAWLING = "It speaks to me.",
		TROPICALFAN = "When I am still, it is as lifeless as Abigail.",
		PALMLEAF_UMBRELLA = "The sun beats down.",

		BOOK_METEOR = "Reading is a dangerous thing.",

		CHESSPIECE_KRAKEN = "A grim reminder of the horrors that lurk in the depths.",
		--CHESSPIECE_TIGERSHARK = "TEMP, put something here",
		--CHESSPIECE_TWISTER = "TEMP, put something here",
		--CHESSPIECE_SEAL = "TEMP, put something here",

		--SWC
		BOAT_SURFBOARD = "It welcomes drowning with open arms.",
		SURFBOARD_ITEM = "It welcomes drowning with open arms.",

		WALANI = {
            GENERIC = "How do you do, %s?",
            ATTACKER = "%s is a madwoman.",
            MURDERER = "I'll send you some place much nicer than this, %s.",
            REVIVER = "Abigail likes your calm exterior, %s.",
            GHOST = "If I get you a heart you won't leave us, right %s?",
			FIRESTARTER = "Douse your fires, %s.",
		},

		WILBUR = {
            GENERIC = "How do you do, %s?",
            ATTACKER = "%s is unstable and restless.",
            MURDERER = "%s must be put down.",
            REVIVER = "Abigail says she understands you, %s.",
            GHOST = "A heart could return %s to this world if they so wished...",
			FIRESTARTER = "%s tires of going unnoticed.",
		},

		WOODLEGS = {
            GENERIC = "How do you do, %s?",
            ATTACKER = "%s is plotting something dastardly with that sword.",
            MURDERER = "%s is a cutthroat killer. As Abigail predicted.",
            REVIVER = "Abigail likes you, %s.",
            GHOST = "A heart could return %s to this world...",
			FIRESTARTER = "Fire setting does not seem in your best interest...",
		},
	},
}
