local IAENV = env
GLOBAL.setfenv(1, GLOBAL)

local AppeasementValue = {
    -- Huge Appeasement
    earring = TUNING.APPEASEMENT_HUGE,
    dustmeringue = TUNING.APPEASEMENT_HUGE,
    -- Large Appeasement
    canary = TUNING.APPEASEMENT_LARGE,
    doydoy = TUNING.APPEASEMENT_LARGE,
    doydoyfeather = TUNING.APPEASEMENT_LARGE,
    mandrake = TUNING.APPEASEMENT_LARGE,
    tigereye = TUNING.APPEASEMENT_LARGE,
    shark_gills = TUNING.APPEASEMENT_LARGE,
    voidcloth = TUNING.APPEASEMENT_LARGE,
    -- Medium Appeasement
    robin = TUNING.APPEASEMENT_MEDIUM,
    robin_winter = TUNING.APPEASEMENT_MEDIUM,
    crow = TUNING.APPEASEMENT_MEDIUM,
    puffin = TUNING.APPEASEMENT_MEDIUM,
    parrot = TUNING.APPEASEMENT_MEDIUM,
    crab = TUNING.APPEASEMENT_MEDIUM,
    lightcrab = TUNING.APPEASEMENT_MEDIUM,
    doydoyegg = TUNING.APPEASEMENT_MEDIUM,
    lobster = TUNING.APPEASEMENT_MEDIUM,
    tallbirdegg = TUNING.APPEASEMENT_MEDIUM,
    wortox_soul = TUNING.APPEASEMENT_MEDIUM,
    horrorfuel = TUNING.APPEASEMENT_MEDIUM,
    purebrilliance = TUNING.APPEASEMENT_MEDIUM,
    -- Small Appeasement
    blubber = TUNING.APPEASEMENT_SMALL,
    butterfly = TUNING.APPEASEMENT_SMALL,
    moonbutterfly = TUNING.APPEASEMENT_SMALL,
    bird_egg = TUNING.APPEASEMENT_SMALL,
    fireflies = TUNING.APPEASEMENT_SMALL,
    solofish_dead = TUNING.APPEASEMENT_SMALL,
    froglegs = TUNING.APPEASEMENT_SMALL,
    hambat = TUNING.APPEASEMENT_SMALL,
    jellyfish_cooked = TUNING.APPEASEMENT_SMALL,
    jellyjerky = TUNING.APPEASEMENT_SMALL,
    mussel = TUNING.APPEASEMENT_SMALL,
    barnacle = TUNING.APPEASEMENT_SMALL,
    nightmarefuel = TUNING.APPEASEMENT_SMALL,
    shark_fin = TUNING.APPEASEMENT_SMALL,
    feather_canary = TUNING.APPEASEMENT_SMALL,
    malbatross_feather = TUNING.APPEASEMENT_SMALL,
    goose_feather = TUNING.APPEASEMENT_SMALL,
    -- Tiny Appeasement
    beardhair = TUNING.APPEASEMENT_TINY,
    boneshard = TUNING.APPEASEMENT_TINY,
    dubloon = TUNING.APPEASEMENT_TINY,
    feather_crow = TUNING.APPEASEMENT_TINY,
    feather_robin = TUNING.APPEASEMENT_TINY,
    feather_robin_winter = TUNING.APPEASEMENT_TINY,
    jellyfish = TUNING.APPEASEMENT_TINY,
    jellyfish_dead = TUNING.APPEASEMENT_TINY,
    limpets = TUNING.APPEASEMENT_TINY,
    cookedmeat = TUNING.APPEASEMENT_TINY,
    cookedmonstermeat = TUNING.APPEASEMENT_TINY,
    cookedsmallmeat = TUNING.APPEASEMENT_TINY,
    monstermeat = TUNING.APPEASEMENT_TINY,
    monstermeat_dried = TUNING.APPEASEMENT_TINY,
    plantmeat = TUNING.APPEASEMENT_TINY,
    plantmeat_cooked = TUNING.APPEASEMENT_TINY,
    smallmeat = TUNING.APPEASEMENT_TINY,
    smallmeat_dried = TUNING.APPEASEMENT_TINY,
    meat_dried = TUNING.APPEASEMENT_TINY,
    meat = TUNING.APPEASEMENT_TINY,
    snakeskin = TUNING.APPEASEMENT_TINY,
    -- Small Wrath
    armorgrass = TUNING.WRATH_SMALL,
    armorwood = TUNING.WRATH_SMALL,
    bedroll_furry = TUNING.WRATH_SMALL,
    bedroll_straw = TUNING.WRATH_SMALL,
    beefalowool = TUNING.WRATH_SMALL,
    boards = TUNING.WRATH_SMALL,
    charcoal = TUNING.WRATH_SMALL,
    cutgrass = TUNING.WRATH_SMALL,
    cutreeds = TUNING.WRATH_SMALL,
    driftwood_log = TUNING.WRATH_SMALL,
    rottenegg = TUNING.WRATH_SMALL,
    fabric = TUNING.WRATH_SMALL,
    foliage = TUNING.WRATH_SMALL,
    guano = TUNING.WRATH_SMALL,
    bamboo = TUNING.WRATH_SMALL,
    vine = TUNING.WRATH_SMALL,
    jungletreeseed = TUNING.WRATH_SMALL,
    lichen = TUNING.WRATH_SMALL,
    livinglog = TUNING.WRATH_SMALL,
    log = TUNING.WRATH_SMALL,
    lureplantbulb = TUNING.WRATH_SMALL,
    blue_cap = TUNING.WRATH_SMALL,
    green_cap = TUNING.WRATH_SMALL,
    red_cap = TUNING.WRATH_SMALL,
    moon_cap = TUNING.WRATH_SMALL,
    red_cap_cooked = TUNING.WRATH_SMALL,
    blue_cap_cooked = TUNING.WRATH_SMALL,
    green_cap_cooked = TUNING.WRATH_SMALL,
    moon_cap_cooked = TUNING.WRATH_SMALL,
    mysterymeat = TUNING.WRATH_SMALL,
    palmleaf = TUNING.WRATH_SMALL,
    papyrus = TUNING.WRATH_SMALL,
    petals_evil = TUNING.WRATH_SMALL,
    petals = TUNING.WRATH_SMALL,
    pinecone = TUNING.WRATH_SMALL,
    palmcone_scale = TUNING.WRATH_SMALL,
    palmcone_seed = TUNING.WRATH_SMALL,
    poop = TUNING.WRATH_SMALL,
    reeds = TUNING.WRATH_SMALL,
    rope = TUNING.WRATH_SMALL,
    spidereggsack = TUNING.WRATH_SMALL,
    spoiled_food = TUNING.WRATH_SMALL,
	spoiled_fish_small = TUNING.WRATH_SMALL,
	spoiled_fish = TUNING.WRATH_SMALL,
	spoiled_fish_large = TUNING.WRATH_SMALL,
    tentaclespots = TUNING.WRATH_SMALL,
    turfs = TUNING.WRATH_SMALL,
    twigs = TUNING.WRATH_SMALL,
    grass_umbrella = TUNING.WRATH_SMALL,
    palmleaf_umbrella = TUNING.WRATH_SMALL,
    dug_marsh_bush = TUNING.WRATH_SMALL,
    dug_coffeebush = TUNING.WRATH_SMALL,
    dug_elephantcactus = TUNING.WRATH_SMALL,
    dug_berrybush = TUNING.WRATH_SMALL,
    dug_berrybush2 = TUNING.WRATH_SMALL,
    dug_berrybush_juicy = TUNING.WRATH_SMALL,
    dug_bananabush = TUNING.WRATH_SMALL,
    dug_monkeytail = TUNING.WRATH_SMALL,
    dug_sapling = TUNING.WRATH_SMALL,
    dug_sapling_moon = TUNING.WRATH_SMALL,
    dug_grass = TUNING.WRATH_SMALL,
    dug_bambootree = TUNING.WRATH_SMALL,
    dug_bush_vine = TUNING.WRATH_SMALL,
    dug_rock_avocado_bush = TUNING.WRATH_SMALL,
    wall_hay_item = TUNING.WRATH_SMALL,
    wall_wood_item = TUNING.WRATH_SMALL,
    -- LARGE Wrath
    nitre = TUNING.WRATH_LARGE,
    obsidian = TUNING.WRATH_LARGE,
    gunpowder = TUNING.WRATH_LARGE,
    cannonball_rock_item = TUNING.WRATH_LARGE,
    canary_poisoned = TUNING.WRATH_LARGE,
    bird_mutant = TUNING.WRATH_LARGE,
    bird_mutant_spitter = TUNING.WRATH_LARGE,
    coconade = TUNING.WRATH_LARGE,
    obsidiancoconade = TUNING.WRATH_LARGE
}

for k, v in pairs(AppeasementValue) do
    IAENV.AddPrefabPostInit(k, function(inst)
        if not TheWorld.ismastersim then
            return
        end

        if not inst.components.appeasement then
            inst:AddComponent("appeasement")
            inst.components.appeasement.appeasementvalue = v
        end
    end)
end
