local wx78_moduledefs=require("wx78_moduledefs")
local AddCreatureScanDataDefinition=wx78_moduledefs.AddCreatureScanDataDefinition
AddCreatureScanDataDefinition("swimminghorror", "maxsanity", 3)
AddCreatureScanDataDefinition("crab", "movespeed", 2)
AddCreatureScanDataDefinition("twister", "movespeed2", 20)
AddCreatureScanDataDefinition("wildbore", "movespeed2", 4)
AddCreatureScanDataDefinition("dragoon", "heat", 4)
AddCreatureScanDataDefinition("flup", "nightvision", 4)
AddCreatureScanDataDefinition("watercrocodog", "cold", 4)
AddCreatureScanDataDefinition("jellyfish_planted", "taser", 5)
AddCreatureScanDataDefinition("rainbowjellyfish_planted", "light", 6)
AddCreatureScanDataDefinition("tigershark", "maxhunger", 6)
AddCreatureScanDataDefinition("doydoy", "maxhunger", 4)
AddCreatureScanDataDefinition("whale_blue", "music", 4)
AddCreatureScanDataDefinition("whale_white", "music", 8)
AddCreatureScanDataDefinition("crocodog", "maxhunger1", 2)
AddCreatureScanDataDefinition("sharx", "maxhunger1", 2)
