local IAENV = env
GLOBAL.setfenv(1, GLOBAL)

local SKILLTREE_DEFS = require("prefabs/skilltree_defs").SKILLTREE_DEFS

SKILLTREE_DEFS.wilson.wilson_alchemy_1.desc = STRINGS.UI.SKILLTREE.WILSON.IA_WILSON_ALCHEMY_1_DESC
SKILLTREE_DEFS.wilson.wilson_alchemy_2.desc = STRINGS.UI.SKILLTREE.WILSON.IA_WILSON_ALCHEMY_2_DESC
SKILLTREE_DEFS.wilson.wilson_alchemy_3.desc = STRINGS.UI.SKILLTREE.WILSON.IA_WILSON_ALCHEMY_3_DESC
SKILLTREE_DEFS.wilson.wilson_alchemy_4.desc = STRINGS.UI.SKILLTREE.WILSON.IA_WILSON_ALCHEMY_4_DESC
-- SKILLTREE_DEFS.wilson.wilson_alchemy_5.desc = STRINGS.UI.SKILLTREE.WILSON.IA_WILSON_ALCHEMY_5_DESC
SKILLTREE_DEFS.wilson.wilson_alchemy_6.desc = STRINGS.UI.SKILLTREE.WILSON.IA_WILSON_ALCHEMY_6_DESC
SKILLTREE_DEFS.wilson.wilson_alchemy_7.desc = STRINGS.UI.SKILLTREE.WILSON.IA_WILSON_ALCHEMY_7_DESC
SKILLTREE_DEFS.wilson.wilson_alchemy_8.desc = STRINGS.UI.SKILLTREE.WILSON.IA_WILSON_ALCHEMY_8_DESC
SKILLTREE_DEFS.wilson.wilson_alchemy_9.desc = STRINGS.UI.SKILLTREE.WILSON.IA_WILSON_ALCHEMY_9_DESC
SKILLTREE_DEFS.wilson.wilson_alchemy_10.desc = STRINGS.UI.SKILLTREE.WILSON.IA_WILSON_ALCHEMY_10_DESC

